services:
  fastapi:
    build: .
    container_name: Diabetes_api
    ports:
    - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  streamlit:
    build: .
    container_name: Diabetes_ui
    ports:
    - "8501:8501"
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0